/* ============================================================================
   BE Mastery — Global Career Readiness Center
   --------------------------------------------------------------------------
   Destination guidance is educational. This module reuses professional-track
   evidence, adaptive priorities, existing mentors and simulations; it does not
   assess immigration, licensing, job eligibility, or employer requirements.
   ============================================================================ */
(function(global){
  const DESTINATIONS=[
    {id:"cameroon",name:"Cameroon",interview:"Prepare a concise introduction, practical experience examples, and respectful questions about the role and site.",culture:"Be clear about reliability, teamwork, safety, and willingness to learn. Confirm expectations directly and professionally.",certification:"Use your current training record as a starting point. Ask employers, training providers, and official authorities which credentials they recognise."},
    {id:"nigeria",name:"Nigeria",interview:"Practise describing technical experience, safety awareness, and how you work with supervisors and teams.",culture:"Use direct but respectful updates. Show readiness to coordinate across teams and follow site procedures.",certification:"Keep a clear record of training, experience, and certificates. Verify employer and authority requirements before applying."},
    {id:"south-africa",name:"South Africa",interview:"Prepare evidence-led answers about quality, safety, procedures, and workplace communication.",culture:"Use clear, respectful language with colleagues, supervisors, and clients. Ask for clarification when a requirement is unclear.",certification:"Map your existing experience and training, then confirm current recognition or trade-test requirements with official sources and employers."},
    {id:"canada",name:"Canada",interview:"Practise structured examples: situation, action, safety decision, and result. Prepare questions about scope and standards.",culture:"Use concise, collaborative communication. State what you know, ask when unsure, and avoid overstating qualifications.",certification:"Requirements vary by province, role, employer, and trade. Treat this center as preparation guidance and verify the current official pathway."},
    {id:"united-states",name:"United States",interview:"Prepare short achievement examples, safety decisions, and a confident explanation of your experience and career direction.",culture:"Communicate directly, professionally, and with practical detail. Confirm priorities and document key workplace information.",certification:"Requirements can vary by state, employer, project, and union context. Confirm current requirements through official and employer channels."},
    {id:"united-kingdom",name:"United Kingdom",interview:"Prepare structured examples with evidence: what the job required, what you did, and how it was checked. Expect questions about execution class and procedure.",culture:"Communicate politely but directly. Raise problems early, confirm instructions in writing where it matters, and expect documented procedures.",certification:"Structural work is executed to EN 1090 and welders qualified to ISO 9606-1. Confirm the execution class and whether UKCA or CE marking applies to the project."},
    {id:"international-contractor",name:"International Contractor",interview:"Prepare a portable professional story: scope of experience, safety record, quality standards, availability, and adaptability.",culture:"Make communication explicit across teams and cultures: confirm assumptions, deadlines, standards, and handovers.",certification:"Organise certificates, references, work history, and translations where appropriate. Verify every destination and project requirement directly."}
  ];
  function state(s){s.careerCenter=s.careerCenter||{destination:"international-contractor",resume:""};return s.careerCenter}
  function destination(s){const id=state(s).destination;return DESTINATIONS.find(x=>x.id===id)||DESTINATIONS[DESTINATIONS.length-1]}
  function gaps(s,t){return global.AdaptiveLearningEngine.skills(s,t).slice(0,4)}
  function readiness(s,t){return global.AdaptiveLearningEngine.prediction(s,t)}
  function pack(s,t){const mentors=(global.trackAiMentors&&global.trackAiMentors())||[],sims=(global.trackSimulations&&global.trackSimulations())||[];const r=global.AdaptiveLearningEngine.recommendation(s,t),at=Math.min(sims.length-1,Math.max(0,global.currentPos().w-1));return {mentor:mentors[Math.min(mentors.length-1,Math.max(0,global.currentPos().w-1))]||mentors[0],simulation:t.id==="general-english"?(sims[at]||sims[0]):null,recommendation:r}}
  function render(s){const t=global.activeProfessionalTrack(),d=destination(s),g=gaps(s,t),p=readiness(s,t),k=pack(s,t),st=state(s);return `<div class="career-center"><div class="eyebrow pg-eyebrow"><button class="back" onclick="go('profile')">‹ Profile</button><span>Career Center</span></div><h1 class="big">Global Career Readiness Center</h1><p class="sub">Prepare your professional story, workplace communication, and practice plan for career opportunities.</p>${(()=>{
      /* The trade decides which codes, vocabulary and model answers the whole
         app assesses against, so it belongs beside the destination rather than
         buried in onboarding where it was chosen once and never seen again. */
      if(!global.Trades||!global.isProfessionalJourney||!global.isProfessionalJourney())return "";
      const cur=global.Trades.active(s);
      return `<section class="card career-trade"><h2>Your profession</h2>
        <div class="career-select">${global.Trades.all().map(x=>`<button class="chip ${x.id===cur.id?"done":""}" onclick="CareerCenter.trade('${global.esc(x.id)}')">${global.esc(x.name)}</button>`).join("")}</div>
        <p><b>${global.esc(cur.name)}</b> — ${global.esc(cur.focus)}</p>
        <div class="sim-skill-chips">${cur.codes.map(c=>`<span>${global.esc(c)}</span>`).join("")}</div>
        <p class="career-pay">${global.esc(cur.pay)} · ${global.esc(cur.payNote)} Indicative only — not an offer, a quote or a survey.</p>
        <p class="career-pay">Changing this changes the standards you are assessed against, the vocabulary your answers are checked for, and the model answers you shadow.</p>
      </section>`;
    })()}<section class="card career-destination"><h2>Career destination</h2><div class="career-select">${DESTINATIONS.map(x=>`<button class="chip ${x.id===d.id?"done":""}" onclick="CareerCenter.select('${x.id}')">${global.esc(x.name)}</button>`).join("")}</div><p><b>${global.esc(d.name)}</b> — educational career preparation only. Always confirm current employer, licensing, and legal requirements with official sources.</p>${(()=>{
      /* Say plainly what choosing this destination changes, so the selector is
         not a label the rest of the app ignores. */
      const j=global.Jurisdictions&&global.Jurisdictions.active(s);
      if(!j)return "";
      return `<div class="career-jur"><b>Your workshop reports are assessed against ${global.esc(j.framework)}</b><p>${global.esc(j.verify)}</p></div>`;
    })()}</section><section class="card career-readiness"><div class="eyebrow">Career readiness</div><div class="career-score"><div><b>${p.career}%</b><span>Career readiness</span></div><div><b>${p.interview}%</b><span>Interview readiness</span></div><div><b>${(()=>{const P=global.AnswerEvaluator&&global.AnswerEvaluator.portfolio(s);return P&&P.hasEvidence?P.answers:"0"})()}</b><span>Spoken answers recorded</span></div></div></section><section class="card career-guidance"><h2>Destination interview guidance</h2><p>${global.esc(d.interview)}</p><h3>Workplace communication and culture</h3><p>${global.esc(d.culture)}</p><h3>Certification roadmap</h3><p>${global.esc(d.certification)}</p></section><section class="card career-gaps"><h2>Career Gap Analysis</h2><p>Your current highest-value growth areas come from your active professional Passport and activity history.</p><div class="career-gap-list">${g.map(x=>`<div><span>${global.esc(x.label)}</span><b>${x.score}%</b><i><em style="width:${x.score}%"></em></i></div>`).join("")}</div><button class="btn btn-p" onclick="CareerCenter.openRecommended()">${global.esc(k.recommendation.title)} →</button></section><section class="card career-resume"><h2>Resume & LinkedIn Coach</h2><p>Write a short professional summary. The coach will return concise, professional rewrites using the existing polishing service when online.</p><textarea id="careerResume" rows="5" placeholder="Example: I am a welder with experience in fabrication...">${global.esc(st.resume||"")}</textarea><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:10px"><button class="btn btn-p" onclick="CareerCenter.polish()">Improve summary →</button><button class="btn btn-g" onclick="go('phrases')">Open Executive Polish</button></div><div id="careerResumeOut"></div></section><section class="card career-packs"><h2>Professional Interview Coaches</h2><p>Choose a coach and practise the interview type for your current professional stage.</p><div class="career-pack-actions">${k.mentor?`<button class="btn btn-p" onclick="go('roleplay','${global.esc(k.mentor.id)}')">Coach: ${global.esc(k.mentor.title)} →</button>`:""}${k.simulation?`<button class="btn btn-g" onclick="go('simulation','${global.esc(k.simulation.id)}')">Simulation: ${global.esc(k.simulation.title)} →</button>`:""}</div></section></div>`}
  function select(id){const s=global.appState();state(s).destination=id;global.save();global.go('career')}
  async function polish(){const s=global.appState(),input=(document.getElementById("careerResume")||{}).value||"",out=document.getElementById("careerResumeOut"),api=typeof POLISH_API!=="undefined"?POLISH_API:"";state(s).resume=input;global.save();if(!input.trim()){if(out)out.textContent="Write a short summary first.";return}if(out)out.textContent="Preparing your professional summary…";try{if(!api||!navigator.onLine)throw new Error("offline");const r=await fetch(api,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text:input.trim(),avoid:[]})});const j=await r.json();if(!r.ok||!Array.isArray(j.versions))throw new Error("unavailable");if(out)out.innerHTML=`<div class="career-polish">${j.versions.slice(0,2).map(v=>`<p><b>${global.esc(v.text)}</b><span>${global.esc(v.learn||"")}</span></p>`).join("")}</div>`}catch(e){if(out)out.innerHTML="<p class=\"sub\">Keep it focused: role, relevant experience, safety or quality standard, and the contribution you want to make.</p>"}}
  function openRecommended(){const s=global.appState(),t=global.activeProfessionalTrack(),r=global.AdaptiveLearningEngine.recommendation(s,t),pos=global.currentPos();global.go(r.go,pos.w,pos.d)}
    function trade(id){
    const st=global.appState();
    if(global.Trades&&global.Trades.setActive(st,id)){global.save();global.go("career")}
  }
  global.CareerCenter=Object.freeze({render,select,trade,polish,openRecommended,destination,gaps,readiness,pack,destinations:DESTINATIONS});
})(window);
