/* lomonec.com/bemastery — English → French. Each entry is an exact string
   from site/bemastery/index.html and its French replacement.
   Kept in English on purpose: the product names the app itself keeps in
   French (Shadow Studio, Practice Partner, Phrase Lab, Executive Polish,
   Premium) and the English practice material shown inside the mock screens
   (the sample sentences, the IPA, the workshop lines). Other names follow
   i18n/fr.json: Feuille de route, Fondations, Défi, Simulations de vie,
   Anglais général, Anglais du soudage. */
const NB = "\u00a0"; // French spacing before : ; ? ! and inside « »
const GET = `Obtenir l'app`;

export default [
  // head
  [`BE Mastery — AI English Speaking Practice`, `BE Mastery — Pratique de l'anglais oral avec l'IA`],
  [`Practise English speaking with AI, shadow real speakers and practise with real learners. BE Mastery is a 25-minutes-a-day speaking app — free on Google Play, and soon on the App Store.`,
   `Entraînez-vous à parler anglais avec l'IA, imitez de vrais orateurs et pratiquez avec de vrais apprenants. BE Mastery est une app d'expression orale, 25 minutes par jour — gratuite sur Google Play, bientôt sur l'App Store.`],
  [`<link rel="canonical" href="https://lomonec.com/bemastery/">`, `<link rel="canonical" href="https://lomonec.com/bemastery/fr/">`],
  [`<meta property="og:url" content="https://lomonec.com/bemastery/">`, `<meta property="og:url" content="https://lomonec.com/bemastery/fr/">`],
  [`Practise with AI. Shadow real speakers. Practise with real people. Download the BE Mastery speaking app — free on Google Play, and soon on the App Store.`,
   `Pratiquez avec l'IA. Imitez de vrais orateurs. Pratiquez avec de vraies personnes. Téléchargez l'app BE Mastery — gratuite sur Google Play, bientôt sur l'App Store.`],
  [`Practise with AI. Shadow real speakers. Practise with real people. Free on Google Play, and soon on the App Store.`,
   `Pratiquez avec l'IA. Imitez de vrais orateurs. Pratiquez avec de vraies personnes. Gratuite sur Google Play, bientôt sur l'App Store.`],
  [`BE Mastery — a speaking practice session shown on a phone`, `BE Mastery — une séance d'expression orale sur un téléphone`],
  [`"url":"https://lomonec.com/bemastery/",`, `"url":"https://lomonec.com/bemastery/fr/",`],
  [`"description":"Practise English speaking with AI, shadow real speakers and practise with real learners. A guided 12-week programme of 25-minute spoken sessions."`,
   `"description":"Entraînez-vous à parler anglais avec l'IA, imitez de vrais orateurs et pratiquez avec de vrais apprenants. Un programme guidé de 12 semaines, en séances orales de 25 minutes."`],

  // bar — data-root sends the script-built links (team, blog) one level up
  [`<body>`, `<body data-root="../">`],
  [`>Skip to content<`, `>Aller au contenu<`],
  [`aria-label="Main"`, `aria-label="Principal"`],
  [`aria-label="Open menu"`, `aria-label="Ouvrir le menu"`],
  [`<summary aria-label="Language: English">`, `<summary aria-label="Langue${NB}: français">`],
  [`<span>EN</span><svg class="chev"`, `<span>FR</span><svg class="chev"`],
  [`lang="en" aria-current="true"`, `lang="en" aria-current="false"`],
  [`lang="fr" aria-current="false"`, `lang="fr" aria-current="true"`],
  [`>Download app<`, `>Télécharger<`],

  // hero
  [`AI + human speaking practice`, `L'oral, avec l'IA et de vraies personnes`],
  [`<span>Speak English</span>`, `<span>Parlez anglais</span>`],
  [`<span>like you belong</span>`, `<span>et prenez enfin</span>`],
  [`<span class="grad">in the room.</span>`, `<span class="grad">votre place.</span>`],
  [`Practise with AI. Shadow real speakers. Practise with real people. Build the confidence for real conversations.`,
   `Pratiquez avec l'IA. Imitez de vrais orateurs. Pratiquez avec de vraies personnes. Gagnez l'assurance des vraies conversations.`],
  [`<p class="cta-kicker">Download BE Mastery</p>`, `<p class="cta-kicker">Téléchargez BE Mastery</p>`],
  [`See how it works`, `Voir comment ça marche`],
  [`Free on Android, iPhone coming soon · Sign in with Apple, Google or email · Your progress follows you between phones · Guidance in 15 languages.`,
   `Gratuit sur Android, bientôt sur iPhone · Connexion avec Apple, Google ou e-mail · Votre progression vous suit d'un téléphone à l'autre · Accompagnement en 15 langues.`],
  [`<b>84</b> guided sessions`, `<b>84</b> séances guidées`],
  [`<b>12</b> weeks`, `<b>12</b> semaines`],
  [`<b>152</b> phrases`, `<b>152</b> expressions`],
  [`<b>25</b> min a day`, `<b>25</b> min par jour`],
  [`<span class="ft">Pronunciation</span><span class="fv"><span class="up">+12%</span> this week</span>`,
   `<span class="ft">Prononciation</span><span class="fv"><span class="up">+12${NB}%</span> cette semaine</span>`],
  [`<span class="fv">Match found</span>`, `<span class="fv">Partenaire trouvé</span>`],
  [`<span class="ft">AI feedback</span><span class="fv">Ready</span>`, `<span class="ft">Retour de l'IA</span><span class="fv">Prêt</span>`],
  [`<span class="ft">Speaking streak</span><span class="fv">7 days</span>`, `<span class="ft">Série d'oral</span><span class="fv">7 jours</span>`],
  [`The BE Mastery app: today's session — the 25-minute practice timer, the phrases to say aloud and the recorder`,
   `L'app BE Mastery${NB}: la séance du jour — le minuteur de 25 minutes, les expressions à dire à voix haute et l'enregistreur`],
  [`<span data-stage-step>Voice</span>`, `<span data-stage-step>Voix</span>`],
  [`<span data-stage-step>Transcript</span>`, `<span data-stage-step>Transcription</span>`],
  [`<span data-stage-step>Analysis</span>`, `<span data-stage-step>Analyse</span>`],
  [`<span data-stage-step>Feedback</span>`, `<span data-stage-step>Retour</span>`],

  // marquee
  [`aria-label="What is inside BE Mastery"`, `aria-label="Ce que contient BE Mastery"`],
  [`</i>Daily 25-minute sessions</span>`, `</i>Séances quotidiennes de 25 minutes</span>`],
  [`</i>AI speaking report</span>`, `</i>Rapport oral par l'IA</span>`],
  [`</i>Translate &amp; IPA</span>`, `</i>Traduction et phonétique</span>`],
  [`</i>Challenge ladder</span>`, `</i>Échelle de Défis</span>`],
  [`</i>Live voice calls</span>`, `</i>Appels vocaux en direct</span>`],
  [`</i>14 Life Simulations</span>`, `</i>14 Simulations de vie</span>`],
  [`</i>Home-screen widgets</span>`, `</i>Widgets d'écran d'accueil</span>`],
  [`</i>Welding English</span>`, `</i>Anglais du soudage</span>`],
  [`</i>10 trades</span>`, `</i>10 métiers</span>`],
  [`</i>Sign in with Apple</span>`, `</i>Connexion avec Apple</span>`],
  [`</i>Sign in with Google</span>`, `</i>Connexion avec Google</span>`],
  [`</i>15 languages</span>`, `</i>15 langues</span>`],

  // screens
  [`aria-label="Screens from the app"`, `aria-label="Écrans de l'app"`],
  [`<span class="dot"></span>Inside BE Mastery</span>`, `<span class="dot"></span>Dans BE Mastery</span>`],
  [`<h2>The real app, <span class="grad">screen by screen</span>.</h2>`, `<h2>La vraie app, <span class="grad">écran par écran</span>.</h2>`],
  [`alt="BE Mastery: Today's session"`, `alt="BE Mastery${NB}: la séance du jour"`],
  [`<b>Today's session</b><span>Timer, phrases to say aloud, your recorder</span>`, `<b>La séance du jour</b><span>Minuteur, expressions à dire, votre enregistreur</span>`],
  [`alt="BE Mastery: The road map"`, `alt="BE Mastery${NB}: la feuille de route"`],
  [`<b>The road map</b><span>Twelve weeks, one beacon: you are here</span>`, `<b>La feuille de route</b><span>Douze semaines, un repère${NB}: vous êtes ici</span>`],
  [`alt="BE Mastery: Practice"`, `alt="BE Mastery${NB}: pratique"`],
  [`<b>Practice</b><span>Every tool, the best one for today first</span>`, `<b>Pratique</b><span>Tous les outils, le meilleur pour aujourd'hui en premier</span>`],
  [`alt="BE Mastery: Phrase Lab"`, `alt="BE Mastery${NB}: Phrase Lab"`],
  [`<b>Phrase Lab</b><span>Say it your way, hear it the boardroom way</span>`, `<b>Phrase Lab</b><span>Dites-le à votre façon, entendez-le comme en réunion de direction</span>`],
  [`alt="BE Mastery: Progress"`, `alt="BE Mastery${NB}: progression"`],
  [`<b>Progress</b><span>Streak, calendar and every report kept</span>`, `<b>Progression</b><span>Série, calendrier et tous vos rapports conservés</span>`],
  [`alt="BE Mastery: Your trend"`, `alt="BE Mastery${NB}: votre tendance"`],
  [`<b>Your trend</b><span>Four skills measured on your own takes</span>`, `<b>Votre tendance</b><span>Quatre compétences mesurées sur vos propres prises</span>`],

  // what's new
  [`<span class="dot"></span>What's new</span>`, `<span class="dot"></span>Nouveautés</span>`],
  [`<h2>Always getting <span class="grad">better</span>.</h2>`, `<h2>Toujours en <span class="grad">progrès</span>.</h2>`],
  [`The latest additions to BE Mastery.`, `Les derniers ajouts à BE Mastery.`],
  [`<span class="new-date">Oct 2026</span>`, `<span class="new-date">oct. 2026</span>`],
  [`<span class="new-date">Sep 2026</span>`, `<span class="new-date">sept. 2026</span>`],
  [`<h3>Coming to iPhone</h3><p>The iPhone app is with Apple for review. One account will carry your progress on both phones.</p>`,
   `<h3>Bientôt sur iPhone</h3><p>L'app iPhone est en cours d'examen chez Apple. Un seul compte portera votre progression sur les deux téléphones.</p>`],
  [`<h3>Sign in with Apple or Google</h3><p>One tap to back up your progress and carry it between iPhone and Android.</p>`,
   `<h3>Connexion avec Apple ou Google</h3><p>Un geste pour sauvegarder votre progression et la retrouver sur iPhone comme sur Android.</p>`],
  [`<h3>Home-screen widgets</h3><p>Your streak, today's step and your Recommendations, without opening the app.</p>`,
   `<h3>Widgets d'écran d'accueil</h3><p>Votre série, l'étape du jour et vos Recommandations, sans ouvrir l'app.</p>`],
  [`<h3>Hear yourself back</h3><p>Every take plays back the moment you stop, and Phrase Lab reads your text aloud.</p>`,
   `<h3>Réécoutez-vous</h3><p>Chaque prise se rejoue dès que vous arrêtez, et Phrase Lab lit votre texte à voix haute.</p>`],
  [`<h3>Welding English studio</h3><p>Ten trades, workplace simulations, interview coaches and real workshop lines to shadow.</p>`,
   `<h3>Le studio Anglais du soudage</h3><p>Dix métiers, des simulations de travail, des coachs d'entretien et de vraies phrases d'atelier à imiter.</p>`],
  [`<h3>Translate and IPA</h3><p>See each Shadow line in your language and in phonetics, word by word.</p>`,
   `<h3>Traduction et phonétique</h3><p>Voyez chaque phrase du Shadowing dans votre langue et en phonétique, mot par mot.</p>`],
  [`<h3>Live practice calls</h3><p>Timed rounds with a real partner, and a private report on your side of the call.</p>`,
   `<h3>Appels de pratique en direct</h3><p>Des manches chronométrées avec un vrai partenaire, et un rapport privé sur votre part de l'appel.</p>`],
  [`<h3>A coach that speaks</h3><p>Your speaking report, read to you by the coach, with corrections and better words.</p>`,
   `<h3>Un coach qui parle</h3><p>Votre rapport oral, lu par le coach, avec des corrections et des mots plus justes.</p>`],

  // 01 problem
  [`<span class="n">01</span> The problem</span>`, `<span class="n">01</span> Le problème</span>`],
  [`<blockquote>Knowing English isn't the same as speaking confidently.</blockquote>`, `<blockquote>Connaître l'anglais, ce n'est pas le parler avec assurance.</blockquote>`],
  [`You read it fine. You follow the meeting. Then it's your turn, and the sentence you had ready arrives a beat too late — so you say the shorter, smaller version instead.`,
   `Vous le lisez sans peine. Vous suivez la réunion. Puis c'est votre tour, et la phrase que vous aviez préparée arrive un temps trop tard — alors vous dites la version plus courte, plus petite.`],
  [`That gap isn't knowledge. It's rehearsal. It closes the same way it closes for musicians and athletes: a little, out loud, every day.`,
   `Cet écart n'est pas une question de connaissances. C'est une question de répétition. Il se comble comme pour les musiciens et les sportifs${NB}: un peu, à voix haute, chaque jour.`],

  // 02 method
  [`<span class="n">02</span> The method</span>`, `<span class="n">02</span> La méthode</span>`],
  [`<h2>Twenty-five minutes. <span class="grad">Every day.</span></h2>`, `<h2>Vingt-cinq minutes. <span class="grad">Chaque jour.</span></h2>`],
  [`One guided session a day for twelve weeks, in four short steps. You don't choose what to study. The road map already knows. You just show up and speak.`,
   `Une séance guidée par jour pendant douze semaines, en quatre étapes courtes. Vous ne choisissez pas quoi étudier. La feuille de route le sait déjà. Vous venez, et vous parlez.`],
  [`<h3>Listen</h3><p>Today's phrases, or a real speaker, and the situation they belong to.</p>`, `<h3>Écouter</h3><p>Les expressions du jour, ou un vrai orateur, et la situation où elles servent.</p>`],
  [`<h3>Practise aloud</h3><p>Shadow it until the rhythm stops feeling foreign.</p>`, `<h3>Pratiquer à voix haute</h3><p>Imitez jusqu'à ce que le rythme ne vous semble plus étranger.</p>`],
  [`<h3>Record</h3><p>Say it in your own voice. This is the part that counts.</p>`, `<h3>Enregistrer</h3><p>Dites-le avec votre propre voix. C'est cette partie qui compte.</p>`],
  [`<h3>Read the report</h3><p>How you came across, what to fix, your sentences rebuilt.</p>`, `<h3>Lire le rapport</h3><p>L'effet que vous avez produit, ce qu'il faut corriger, vos phrases reconstruites.</p>`],

  // 03 inside
  [`<span class="n">03</span> Inside the app</span>`, `<span class="n">03</span> Dans l'app</span>`],
  [`<h2>Everything you need to <span class="grad">speak, not just study</span>.</h2>`, `<h2>Tout ce qu'il faut pour <span class="grad">parler, pas seulement étudier</span>.</h2>`],
  [`Open the app and your page is already waiting: today's session first, then the practice that fits it.`,
   `Ouvrez l'app et votre page vous attend déjà${NB}: la séance du jour d'abord, puis la pratique qui l'accompagne.`],
  [`<h3>Life Simulations</h3><p>Practise a real conversation — the interview, the stand-up, the salary talk — before it happens.</p>`,
   `<h3>Simulations de vie</h3><p>Répétez une vraie conversation — l'entretien, le point d'équipe, la négociation de salaire — avant qu'elle n'ait lieu.</p>`],
  [`<p>Speak with another learner who is practising right now, or call them live.</p>`, `<p>Parlez avec un autre apprenant qui s'entraîne en ce moment, ou appelez-le en direct.</p>`],
  [`<p>Say it your way, hear it the boardroom way.</p>`, `<p>Dites-le à votre façon, entendez-le comme en réunion de direction.</p>`],
  [`<h3>Grammar exercises</h3><p>Short, interactive drills on the grammar you actually use when you speak.</p>`,
   `<h3>Exercices de grammaire</h3><p>Des exercices courts et interactifs sur la grammaire que vous utilisez vraiment à l'oral.</p>`],
  [`<h3>Your words</h3><p>The words you stumbled on come back until they stop being a stumble.</p>`,
   `<h3>Vos mots</h3><p>Les mots sur lesquels vous avez buté reviennent jusqu'à ce qu'ils ne vous arrêtent plus.</p>`],
  [`<h3>Road map</h3><p>Twelve weeks, one day at a time. You always know what comes next.</p>`,
   `<h3>Feuille de route</h3><p>Douze semaines, un jour à la fois. Vous savez toujours ce qui vient ensuite.</p>`],
  [`<span>There is more inside than we show here.</span>`, `<span>L'app contient bien plus que ce que nous montrons ici.</span>`],
  [`data-ev-source="inside">Open it in the app`, `data-ev-source="inside">Découvrez-la dans l'app`],

  // 04 shadow studio
  [`<h2>Borrow the rhythm of someone who <span class="grad">already sounds right</span>.</h2>`, `<h2>Empruntez le rythme de quelqu'un qui <span class="grad">sonne déjà juste</span>.</h2>`],
  [`Pick a real talk, interview or lesson. Watch it with the words lighting up, shadow it one paragraph at a time, then say it without looking. When you do, it's yours.`,
   `Choisissez une vraie conférence, un entretien ou une leçon. Regardez-la pendant que les mots s'allument, imitez-la paragraphe par paragraphe, puis dites-la sans regarder. À ce moment-là, elle est à vous.`],
  [`aria-label="Shadow Studio pages"`, `aria-label="Pages de Shadow Studio"`],
  [`aria-selected="true">Watch</button>`, `aria-selected="true">Regarder</button>`],
  [`aria-selected="false">Shadow</button>`, `aria-selected="false">Shadowing</button>`],
  [`aria-selected="false">Challenge</button>`, `aria-selected="false">Défi</button>`],
  [`<span><b>Watch</b> — the video stays on top and the transcript runs underneath in short paragraphs, with the word being said lit up.</span>`,
   `<span><b>Regarder</b> — la vidéo reste en haut et la transcription défile dessous en courts paragraphes, le mot prononcé mis en lumière.</span>`],
  [`<span><b>Shadow</b> — the clip loops on one paragraph. Tap a word to hear it, see the line in your own language and in IPA, then record.</span>`,
   `<span><b>Shadowing</b> — l'extrait tourne en boucle sur un paragraphe. Touchez un mot pour l'entendre, voyez la phrase dans votre langue et en phonétique, puis enregistrez.</span>`],
  [`<span><b>Challenge</b> — the same paragraph with less help each time, until you can say it unseen and then in your own words.</span>`,
   `<span><b>Défi</b> — le même paragraphe avec un peu moins d'aide à chaque fois, jusqu'à pouvoir le dire sans texte, puis avec vos propres mots.</span>`],
  [`<span>Shadow Studio lives in the app.</span>`, `<span>Shadow Studio se trouve dans l'app.</span>`],
  [`">Get the app`, `">${GET}`],
  [`<span class="st-title">Give a clear update in the stand-up</span>`, `<span class="st-title">Faire un point clair en réunion d'équipe</span>`],
  [`aria-label="Watch"`, `aria-label="Regarder"`],
  [`aria-label="Shadow" hidden`, `aria-label="Shadowing" hidden`],
  [`aria-label="Challenge" hidden`, `aria-label="Défi" hidden`],
  [`<span>Original transcript</span>`, `<span>Transcription originale</span>`],
  [`</svg>Translate</span>`, `</svg>Traduire</span>`],
  [`</svg>Pronunciation</span>`, `</svg>Prononciation</span>`],
  [`The clip loops on this paragraph. Tap a word to hear it, translate it, then record.`,
   `L'extrait tourne en boucle sur ce paragraphe. Touchez un mot pour l'entendre, traduisez-le, puis enregistrez.`],
  [`<div class="st-eyebrow">Did you hear it?</div>`, `<div class="st-eyebrow">Vous l'avez entendu${NB}?</div>`],
  [`aria-label="Challenge steps"`, `aria-label="Étapes du Défi"`],
  [`<li class="on">Listen</li><li>Together</li><li>From memory</li><li>Unseen</li><li>In your words</li>`,
   `<li class="on">Écouter</li><li>Ensemble</li><li>De mémoire</li><li>Sans texte</li><li>Avec vos mots</li>`],
  [`</svg>Check</div>`, `</svg>Vérifier</div>`],
  [`</svg>Shadow</span>`, `</svg>Shadowing</span>`],
  [`<div class="sm-k">The library</div>`, `<div class="sm-k">La bibliothèque</div>`],
  [`<h3>Hundreds of real videos, sorted for work.</h3>`, `<h3>Des centaines de vraies vidéos, classées pour le travail.</h3>`],
  [`</svg>What do you want to practise?</div>`, `</svg>Que voulez-vous pratiquer${NB}?</div>`],
  [`<span class="on">For you</span><span>Meetings</span><span>Presentations</span><span>Interviews</span><span>Everyday</span>`,
   `<span class="on">Pour vous</span><span>Réunions</span><span>Présentations</span><span>Entretiens</span><span>Quotidien</span>`],
  [`<b>This week · Week 1</b><i>Fits your plan</i>`, `<b>Cette semaine · Semaine 1</b><i>Adapté à votre plan</i>`],
  [`<b>Meetings · 11 min</b><i class="tx">Transcript</i>`, `<b>Réunions · 11 min</b><i class="tx">Transcription</i>`],
  [`<p>Search by topic, or take the pick for this week of your plan. Any video link works too.</p>`,
   `<p>Cherchez par thème, ou prenez la sélection de la semaine de votre plan. N'importe quel lien vidéo fonctionne aussi.</p>`],
  [`<div class="sm-k">The Challenge</div>`, `<div class="sm-k">Le Défi</div>`],
  [`<h3>Less help every round. The app decides when.</h3>`, `<h3>Moins d'aide à chaque manche. L'app décide quand.</h3>`],
  [`<li><b>Listen</b></li>`, `<li><b>Écouter</b></li>`],
  [`<li><b>Together</b></li>`, `<li><b>Ensemble</b></li>`],
  [`<li><b>From memory</b></li>`, `<li><b>De mémoire</b></li>`],
  [`<li><b>Unseen</b></li>`, `<li><b>Sans texte</b></li>`],
  [`<li><b>In your words</b></li>`, `<li><b>Avec vos mots</b></li>`],
  [`<p>Five rounds, each with less help, until the sentence is yours.</p>`, `<p>Cinq manches, chacune avec moins d'aide, jusqu'à ce que la phrase soit à vous.</p>`],
  [`<div class="sm-k">After every take</div>`, `<div class="sm-k">Après chaque prise</div>`],
  [`<h3>One screen. One word to fix.</h3>`, `<h3>Un écran. Un mot à corriger.</h3>`],
  [`<span class="rep-ok">Shadow complete</span><span class="rep-v">A solid start — let's fix one word.</span>`,
   `<span class="rep-ok">Shadowing terminé</span><span class="rep-v">Un bon début — corrigeons un mot.</span>`],
  [`<span><i>Words clear</i><b>12 / 14</b></span><span><i>Pace</i><b>Natural</b></span>`, `<span><i>Mots clairs</i><b>12 / 14</b></span><span><i>Débit</i><b>Naturel</b></span>`],
  [`<i>Today's focus</i>`, `<i>Le point du jour</i>`],
  [`<div class="rep-steps"><span>Listen</span><span>Say it</span><span>Compare</span></div>`, `<div class="rep-steps"><span>Écouter</span><span>Le dire</span><span>Comparer</span></div>`],
  [`<p>Every report is kept, with the words that tripped you, so you pick up where you left off.</p>`,
   `<p>Chaque rapport est conservé, avec les mots qui vous ont fait buter, pour reprendre là où vous en étiez.</p>`],
  [`The library, Watch, Shadow and Challenge are part of General English. Translation and pronunciation are written by AI and need a connection. The report above is an example; yours is built from your own recording.`,
   `La bibliothèque, Regarder, Shadowing et Défi font partie de l'Anglais général. La traduction et la prononciation sont rédigées par l'IA et demandent une connexion. Le rapport ci-dessus est un exemple${NB}; le vôtre est construit à partir de votre propre enregistrement.`],

  // 05 AI practice
  [`<span class="ttl">Your speaking report</span>`, `<span class="ttl">Votre rapport oral</span>`],
  [`<span>Listen</span><span class="on">Fix</span><span>Build</span><span>Upgrade</span><span>Say it again</span>`,
   `<span>Écouter</span><span class="on">Corriger</span><span>Construire</span><span>Enrichir</span><span>Redire</span>`],
  [`How you came across · 131 words in 62 seconds`, `L'effet produit · 131 mots en 62 secondes`],
  [`<div class="who">You said</div>`, `<div class="who">Vous avez dit</div>`],
  [`<span class="ai">AI</span> · what you should have said`, `<span class="ai">IA</span> · ce qu'il fallait dire`],
  [`<b>since</b> + a start point takes <i>have been</i> + -ing`, `<b>since</b> + un point de départ appelle <i>have been</i> + -ing`],
  [`<span class="k">Upgrade</span><b>get it over the line</b><span class="d">to finish something that was hard to complete</span>`,
   `<span class="k">Enrichir</span><b>get it over the line</b><span class="d">venir à bout de quelque chose de difficile à terminer</span>`],
  [`<span><b>Say it better</b> — hear the whole minute said the way a professional would, as often as you want.</span>`,
   `<span><b>Dites-le mieux</b> — écoutez toute la minute dite comme le ferait un professionnel, autant de fois que vous voulez.</span>`],
  [`<span class="n">05</span> AI practice</span>`, `<span class="n">05</span> Pratique avec l'IA</span>`],
  [`<h2>Practise before the <span class="grad">real conversation</span>.</h2>`, `<h2>Répétez avant la <span class="grad">vraie conversation</span>.</h2>`],
  [`Talk for a minute about your project, your role or the update you owe someone. The report tells you how you came across, fixes what you got wrong, rebuilds your sentences and gives you better words. Then the coach reads it to you.`,
   `Parlez une minute de votre projet, de votre rôle ou du point que vous devez faire à quelqu'un. Le rapport vous dit quel effet vous avez produit, corrige vos erreurs, reconstruit vos phrases et vous donne des mots plus justes. Puis le coach vous le lit.`],
  [`<b>14 Life Simulations:</b> a job interview, a salary negotiation, the daily stand-up, a hotel check-in. The character answers you out loud.`,
   `<b>14 Simulations de vie${NB}:</b> un entretien d'embauche, une négociation de salaire, le point quotidien d'équipe, l'arrivée à l'hôtel. Le personnage vous répond à voix haute.`],
  [`<b>In every daily session:</b> record yourself and the report comes back, judged against that day's task.`,
   `<b>Dans chaque séance quotidienne${NB}:</b> enregistrez-vous et le rapport revient, évalué selon la tâche du jour.`],
  [`Anything written by AI is labelled as AI. It coaches you. It never pretends to be a person.`,
   `Tout ce qui est rédigé par l'IA est signalé comme tel. L'IA vous coache. Elle ne se fait jamais passer pour une personne.`],
  [`<span>Rehearse it on your phone, out loud.</span>`, `<span>Répétez sur votre téléphone, à voix haute.</span>`],

  // 06 practice partner
  [`<h2>AI can help you practise. <span class="grad">People help you use it.</span></h2>`,
   `<h2>L'IA vous aide à pratiquer. <span class="grad">Les gens vous aident à vous en servir.</span></h2>`],
  [`See who else is practising right now and work through today's speaking task together — in short voice turns, or on a live call.`,
   `Voyez qui d'autre s'entraîne en ce moment et faites ensemble la tâche orale du jour — en courts messages vocaux, ou en appel direct.`],
  [`<b>Practise live:</b> a real-time voice call with the person you are practising with. Nothing is recorded.`,
   `<b>Pratiquer en direct${NB}:</b> un appel vocal en temps réel avec la personne avec qui vous pratiquez. Rien n'est enregistré.`],
  [`<b>Nobody there yet?</b> The AI coach is always one tap away, clearly marked as AI.`,
   `<b>Personne pour l'instant${NB}?</b> Le coach IA est toujours à portée de main, clairement signalé comme IA.`],
  [`First names only. No photos, no profiles, no feed. Leave or block at any time.`,
   `Prénoms uniquement. Pas de photos, pas de profils, pas de fil d'actualité. Partez ou bloquez à tout moment.`],
  [`Practice Partner is part of General English and is for adults (18+).`,
   `Practice Partner fait partie de l'Anglais général et s'adresse aux adultes (18${NB}ans et plus).`],
  [`<span>Practice Partner is in the app.</span>`, `<span>Practice Partner est dans l'app.</span>`],
  [`<span class="av">You</span>Today's speaking task`, `<span class="av">Vous</span>La tâche orale du jour`],
  [`<span class="nnode core">Who is practising now</span>`, `<span class="nnode core">Qui s'entraîne maintenant</span>`],
  [`<p class="netcap">Pick someone, or be picked</p>`, `<p class="netcap">Choisissez quelqu'un, ou soyez choisi</p>`],
  [`<span class="tagline">B1 · evenings</span>`, `<span class="tagline">B1 · le soir</span>`],
  [`<span class="tagline">B2 · mornings</span>`, `<span class="tagline">B2 · le matin</span>`],
  [`<span class="tagline">B1 · weekends</span>`, `<span class="tagline">B1 · le week-end</span>`],
  [`<span class="nnode">Take turns</span>`, `<span class="nnode">Chacun son tour</span>`],
  [`<span class="ldot" aria-hidden="true"></span>Practise live</span>`, `<span class="ldot" aria-hidden="true"></span>Pratiquer en direct</span>`],
  [`<span class="nnode out">Feedback → practise again</span>`, `<span class="nnode out">Retour → nouvelle pratique</span>`],

  // 07 progress
  [`<span class="n">07</span> Progress</span>`, `<span class="n">07</span> Progression</span>`],
  [`<h2>See yourself <span class="grad">improve</span>.</h2>`, `<h2>Voyez-vous <span class="grad">progresser</span>.</h2>`],
  [`Not a percentage of a course. The same four things measured on the takes you actually recorded, round after round, so improvement is something you can point at.`,
   `Pas un pourcentage de cours terminé. Les mêmes quatre critères, mesurés sur les prises que vous avez vraiment enregistrées, manche après manche${NB}: vos progrès se voient.`],
  [`<span class="ttl">Speaking report</span>`, `<span class="ttl">Rapport oral</span>`],
  [`<span>Round 1</span><span>Round 2</span><span>Round 3</span><span>Round 4</span>`, `<span>Manche 1</span><span>Manche 2</span><span>Manche 3</span><span>Manche 4</span>`],
  [`<span class="name">Pronunciation</span>`, `<span class="name">Prononciation</span>`],
  [`<span class="name">Vocabulary</span>`, `<span class="name">Vocabulaire</span>`],
  [`<span class="name">Fluency</span>`, `<span class="name">Aisance</span>`],
  [`An illustration of the report shape — your own numbers come from your own recordings.`,
   `Une illustration de la forme du rapport — vos chiffres viennent de vos propres enregistrements.`],
  [`A streak and a lit-up calendar for the habit itself — six days a week is the target, not seven.`,
   `Une série et un calendrier qui s'allume pour l'habitude elle-même — l'objectif est six jours par semaine, pas sept.`],
  [`Every report is kept: your Shadow history, every Life Simulation attempt, and the words that keep coming back across sessions.`,
   `Chaque rapport est conservé${NB}: votre historique de Shadowing, chaque essai de Simulation de vie, et les mots qui reviennent d'une séance à l'autre.`],
  [`Words you stumbled on return on a spacing schedule until they stop being a stumble.`,
   `Les mots sur lesquels vous avez buté reviennent à intervalles espacés jusqu'à ce qu'ils ne vous arrêtent plus.`],
  [`Example certificate of completion for a sample learner, Alex Johnson, Business English Mastery`,
   `Exemple de certificat de fin de programme pour un apprenant fictif, Alex Johnson, Business English Mastery`],
  [`<b>Your certificate</b>`, `<b>Votre certificat</b>`],
  [`Finish all 84 sessions and it unlocks with your name on it. Download it as a PDF or share it.`,
   `Terminez les 84 séances et il se débloque à votre nom. Téléchargez-le en PDF ou partagez-le.`],
  [`It shows you completed the programme. It is not an English-level test. Example shown.`,
   `Il atteste que vous avez terminé le programme. Ce n'est pas un test de niveau d'anglais. Exemple présenté.`],
  [`data-l="a">Guided sessions<`, `data-l="a">Séances guidées<`],
  [`data-l="b">Phrases<`, `data-l="b">Expressions<`],
  [`data-l="c">Languages<`, `data-l="c">Langues<`],
  [`Works offline. Recordings are saved on your device — we never keep a copy.`,
   `Fonctionne hors ligne. Les enregistrements restent sur votre appareil — nous n'en gardons jamais de copie.`],

  // 08 widgets
  [`The Recommendations widget: four picks for today, each with a picture, what it is and why it was chosen`,
   `Le widget Recommandations${NB}: quatre choix pour aujourd'hui, chacun avec une image, ce que c'est et pourquoi il a été choisi`],
  [`The medium road-map widget: a 12-day streak ring, today's step and the button to continue Week 3`,
   `Le widget moyen de la feuille de route${NB}: un anneau de série de 12 jours, l'étape du jour et le bouton pour continuer la semaine 3`],
  [`The small widget: the streak and today's step`, `Le petit widget${NB}: la série et l'étape du jour`],
  [`A locked widget in grey: Go Premium to unlock this widget`, `Un widget verrouillé, en gris${NB}: passez à Premium pour débloquer ce widget`],
  [`<span class="n">08</span> On your home screen</span>`, `<span class="n">08</span> Sur votre écran d'accueil</span>`],
  [`<h2>Your next step, <span class="grad">before you even open the app</span>.</h2>`, `<h2>Votre prochaine étape, <span class="grad">avant même d'ouvrir l'app</span>.</h2>`],
  [`Widgets for iPhone and Android show your streak, today's step and your place on the road map. One tap lands on the exact lesson.`,
   `Les widgets pour iPhone et Android affichent votre série, l'étape du jour et votre place sur la feuille de route. Un geste vous amène à la leçon exacte.`],
  [`<b>Small, medium and large,</b> plus the lock screen on iPhone. A General English and a Welding English widget, side by side if you study both.`,
   `<b>Petit, moyen et grand,</b> plus l'écran verrouillé sur iPhone. Un widget Anglais général et un widget Anglais du soudage, côte à côte si vous suivez les deux.`],
  [`<b>Recommendations:</b> what the app picked for you today — videos, challenges, practice — with pictures, one tap from your home screen.`,
   `<b>Recommandations${NB}:</b> ce que l'app a choisi pour vous aujourd'hui — vidéos, défis, pratique — avec des images, à un geste de votre écran d'accueil.`],
  [`The flame and the message follow the clock: done, waiting, or keep your streak alive tonight.`,
   `La flamme et le message suivent l'heure${NB}: fait, en attente, ou gardez votre série en vie ce soir.`],
  [`Sign in to use the widgets. The larger widgets and Recommendations are part of Premium.`,
   `Connectez-vous pour utiliser les widgets. Les grands widgets et les Recommandations font partie de Premium.`],
  [`<h3 class="shots-h" data-reveal>On your home screen</h3>`, `<h3 class="shots-h" data-reveal>Sur votre écran d'accueil</h3>`],
  [`A home screen with the small and the large BE Mastery widgets: a 12-day streak, today's step and the road map`,
   `Un écran d'accueil avec le petit et le grand widget BE Mastery${NB}: une série de 12 jours, l'étape du jour et la feuille de route`],
  [`<b>Small and large</b><span>Streak, today's step, the road map</span>`, `<b>Petit et grand</b><span>Série, étape du jour, feuille de route</span>`],
  [`A home screen with the Recommendations widget and the medium widget`, `Un écran d'accueil avec le widget Recommandations et le widget moyen`],
  [`<b>Recommended for you</b><span>Today's picks, one tap away</span>`, `<b>Recommandé pour vous</b><span>Les choix du jour, à un geste</span>`],
  [`A home screen with a Welding English widget, a General English widget and a locked Recommendations widget`,
   `Un écran d'accueil avec un widget Anglais du soudage, un widget Anglais général et un widget Recommandations verrouillé`],
  [`<b>Both programmes</b><span>Welding and General English side by side</span>`, `<b>Les deux programmes</b><span>Soudage et Anglais général côte à côte</span>`],

  // 09 who
  [`<span class="n">09</span> Who it's for</span>`, `<span class="n">09</span> Pour qui</span>`],
  [`<h2>For the moment <span class="grad">it's your turn to speak</span>.</h2>`, `<h2>Pour le moment où <span class="grad">c'est à vous de parler</span>.</h2>`],
  [`<b>In meetings</b><p>You follow every word, then freeze when it's your turn. Rehearse the update before you give it.</p>`,
   `<b>En réunion</b><p>Vous suivez chaque mot, puis vous vous figez quand c'est votre tour. Répétez votre point avant de le présenter.</p>`],
  [`<b>Before an interview</b><p>Answer the questions out loud, hear how you came across, and fix it before the day.</p>`,
   `<b>Avant un entretien</b><p>Répondez aux questions à voix haute, écoutez l'effet produit, et corrigez avant le jour J.</p>`],
  [`<b>Moving abroad for work</b><p>Settle in faster: small talk, handovers, calls and the paperwork conversations.</p>`,
   `<b>Partir travailler à l'étranger</b><p>Installez-vous plus vite${NB}: conversations informelles, passations, appels et échanges administratifs.</p>`],
  [`<b>Skilled trades</b><p>Welders get their own programme: the workshop, safety, quality checks and the interview.</p>`,
   `<b>Métiers qualifiés</b><p>Les soudeurs ont leur propre programme${NB}: l'atelier, la sécurité, les contrôles qualité et l'entretien.</p>`],

  // 10 paths
  [`<span class="n">10</span> Two programmes</span>`, `<span class="n">10</span> Deux programmes</span>`],
  [`<h2>Two paths. One goal: <span class="grad">confident communication</span>.</h2>`, `<h2>Deux parcours. Un objectif${NB}: <span class="grad">communiquer avec assurance</span>.</h2>`],
  [`Pick the one that matches the room you actually walk into. They are separate programmes with separate progress — switch whenever you like.`,
   `Choisissez celui qui correspond au monde où vous travaillez vraiment. Ce sont deux programmes distincts, avec chacun sa progression — changez quand vous voulez.`],
  [`<span class="tag">General English</span>`, `<span class="tag">Anglais général</span>`],
  [`<h3>For meetings, interviews and everyday work</h3>`, `<h3>Pour les réunions, les entretiens et le travail au quotidien</h3>`],
  [`The full speaking system, from foundations to executive communication.`, `Le système complet d'expression orale, des bases à la communication de dirigeant.`],
  [`<span>Daily speaking practice and a 12-week road map</span>`, `<span>Une pratique orale quotidienne et une feuille de route de 12 semaines</span>`],
  [`<span>Shadow Studio: hundreds of real videos to watch, shadow and master</span>`, `<span>Shadow Studio${NB}: des centaines de vraies vidéos à regarder, imiter et maîtriser</span>`],
  [`<span>Practice Partner: voice turns or live calls with real people</span>`, `<span>Practice Partner${NB}: messages vocaux ou appels en direct avec de vraies personnes</span>`],
  [`<span>The speaking report, Phrase Lab, grammar exercises and 14 Life Simulations</span>`, `<span>Le rapport oral, Phrase Lab, des exercices de grammaire et 14 Simulations de vie</span>`],
  [`Practice Partner and human practice belong to this programme only.`, `Practice Partner et la pratique avec des personnes n'existent que dans ce programme.`],
  [`<span class="tag">Welding professional English</span>`, `<span class="tag">Anglais professionnel du soudage</span>`],
  [`<h3>For the workshop, the site and the interview</h3>`, `<h3>Pour l'atelier, le chantier et l'entretien</h3>`],
  [`A technical programme built around the conversations a welder actually has.`, `Un programme technique construit autour des conversations qu'un soudeur a vraiment.`],
  [`<span>Technical vocabulary and workshop communication</span>`, `<span>Vocabulaire technique et communication en atelier</span>`],
  [`<span>Safety briefings, quality checks and handovers</span>`, `<span>Consignes de sécurité, contrôles qualité et passations</span>`],
  [`<span>Workshop interviews, with a report from each interviewer</span>`, `<span>Entretiens d'atelier, avec un rapport de chaque recruteur</span>`],
  [`<span>Professional interview coaches, judged against the trade's own standards</span>`, `<span>Des coachs d'entretien professionnels, évalués selon les normes du métier</span>`],
  [`aria-label="Workshop communication chain"`, `aria-label="Chaîne de communication en atelier"`],
  [`<span>Supervisor</span><i>→</i><span>Worker</span><i>→</i><span>Safety</span><i>→</i><span>QA</span><i>→</i><span>Interview</span>`,
   `<span>Chef d'équipe</span><i>→</i><span>Ouvrier</span><i>→</i><span>Sécurité</span><i>→</i><span>Qualité</span><i>→</i><span>Entretien</span>`],
  [`Starts with fifteen days of Foundations in your own language if you need them.`, `Commence par quinze jours de Fondations dans votre langue si vous en avez besoin.`],

  // 11 welding
  [`<span class="n">11</span> Welding English</span>`, `<span class="n">11</span> Anglais du soudage</span>`],
  [`<h2>English for the workshop, <span class="grad">the site and the interview</span>.</h2>`, `<h2>L'anglais de l'atelier, <span class="grad">du chantier et de l'entretien</span>.</h2>`],
  [`A programme of its own for skilled trades. You practise the sentences a supervisor, an inspector and an interviewer actually say — and the answers they expect back.`,
   `Un programme à part pour les métiers qualifiés. Vous pratiquez les phrases que disent vraiment un chef d'équipe, un inspecteur et un recruteur — et les réponses qu'ils attendent.`],
  [`<b>Practice text shadowing:</b> real lines from your workshops. Hear each one, read it, say it back — the way you will answer on the job.`,
   `<b>Shadowing de textes${NB}:</b> de vraies phrases tirées de vos ateliers. Écoutez chacune, lisez-la, répétez-la — comme vous répondrez au travail.`],
  [`<b>Workplace simulations and interview coaches:</b> the toolbox talk, the permit, the handover and the hiring interview, each with a report against the trade's own standards.`,
   `<b>Simulations de travail et coachs d'entretien${NB}:</b> le quart d'heure sécurité, le permis de travail, la passation et l'entretien d'embauche, chacun avec un rapport selon les normes du métier.`],
  [`<b>Foundations in your own language:</b> fifteen days of first sentences for anyone starting from the beginning.`,
   `<b>Fondations dans votre langue${NB}:</b> quinze jours de premières phrases pour celles et ceux qui partent de zéro.`],
  [`<span>Choose Welding English when you open the app.</span>`, `<span>Choisissez Anglais du soudage à l'ouverture de l'app.</span>`],
  [`<div class="wd-k">Ten trades, one programme</div>`, `<div class="wd-k">Dix métiers, un programme</div>`],
  [`style="--i:0">Welder</span>`, `style="--i:0">Soudeur</span>`],
  [`style="--i:1">Pipefitter</span>`, `style="--i:1">Tuyauteur</span>`],
  [`style="--i:2">Boilermaker</span>`, `style="--i:2">Chaudronnier</span>`],
  [`style="--i:3">Millwright</span>`, `style="--i:3">Mécanicien industriel</span>`],
  [`style="--i:4">Refinery Operator</span>`, `style="--i:4">Opérateur de raffinerie</span>`],
  [`style="--i:5">Instrumentation Technician</span>`, `style="--i:5">Technicien instrumentation</span>`],
  [`style="--i:6">Industrial Electrician</span>`, `style="--i:6">Électricien industriel</span>`],
  [`style="--i:7">HSE Officer</span>`, `style="--i:7">Responsable HSE</span>`],
  [`style="--i:8">NDT Technician</span>`, `style="--i:8">Technicien CND</span>`],
  [`style="--i:9">Process Engineer</span>`, `style="--i:9">Ingénieur procédés</span>`],
  [`The Welding English widget: a 5-day streak and today's step, Report a weld defect clearly`,
   `Le widget Anglais du soudage${NB}: une série de 5 jours et l'étape du jour, Report a weld defect clearly`],
  [`<span class="wd-who">Supervisor</span>`, `<span class="wd-who">Chef d'équipe</span>`],
  [`<span class="wd-who you">You</span>`, `<span class="wd-who you">Vous</span>`],
  [`<span>stages, from the first day in the workshop to the interview</span>`, `<span>étapes, du premier jour à l'atelier jusqu'à l'entretien</span>`],
  [`<span>sessions of 25 minutes</span>`, `<span>séances de 25 minutes</span>`],
  [`<span>trades, each with its own workshop lines</span>`, `<span>métiers, chacun avec ses propres phrases d'atelier</span>`],
  [`<span>days of Foundations in your language</span>`, `<span>jours de Fondations dans votre langue</span>`],
  [`<h3 class="shots-h" data-reveal>Built for the workshop</h3>`, `<h3 class="shots-h" data-reveal>Conçu pour l'atelier</h3>`],
  [`<h3>Workplace simulations</h3><p>Talk it through before the shift — the handover, the permit, the safety stop, the first day in a new workshop.</p>`,
   `<h3>Simulations de travail</h3><p>Répétez avant votre poste — la passation, le permis, l'arrêt de sécurité, le premier jour dans un nouvel atelier.</p>`],
  [`<h3>Trade vocabulary</h3><p>Torch, arc, root pass, weld bead: the words of your trade, heard and said in real sentences.</p>`,
   `<h3>Vocabulaire du métier</h3><p>Torch, arc, root pass, weld bead${NB}: les mots de votre métier, entendus et dits dans de vraies phrases.</p>`],
  [`<h3>Grammar for the job</h3><p>Short drills built from workshop sentences — the grammar you need to report, ask and confirm.</p>`,
   `<h3>La grammaire du travail</h3><p>Des exercices courts tirés de phrases d'atelier — la grammaire qu'il faut pour signaler, demander et confirmer.</p>`],
  [`<h3>Your words</h3><p>Every word you trip on comes back with its sound and meaning until it sticks.</p>`,
   `<h3>Vos mots</h3><p>Chaque mot sur lequel vous butez revient avec sa prononciation et son sens, jusqu'à ce qu'il reste.</p>`],
  [`<h3>Road map</h3><p>Twelve stages, from your first day in the workshop to the hiring interview. You always know the next step.</p>`,
   `<h3>Feuille de route</h3><p>Douze étapes, de votre premier jour à l'atelier jusqu'à l'entretien d'embauche. Vous connaissez toujours la prochaine étape.</p>`],
  [`<h3>Career readiness</h3><p>See how completely you explain your work in English, measured against your trade's expectations.</p>`,
   `<h3>Préparation à l'emploi</h3><p>Voyez à quel point vous expliquez votre travail en anglais, au regard des attentes de votre métier.</p>`],
  [`<h3 class="shots-h" data-reveal>Inside Welding English</h3>`, `<h3 class="shots-h" data-reveal>Dans Anglais du soudage</h3>`],
  [`Welding English: the 12-stage road map, Stage 1 Entering the Workshop`, `Anglais du soudage${NB}: la feuille de route en 12 étapes, étape 1 Entering the Workshop`],
  [`<b>The road map</b><span>Twelve stages, workshop to interview</span>`, `<b>La feuille de route</b><span>Douze étapes, de l'atelier à l'entretien</span>`],
  [`Welding English: Practice, with the best tool for today's step`, `Anglais du soudage${NB}: Pratique, avec le meilleur outil pour l'étape du jour`],
  [`<b>Practice</b><span>The best tool for today's step, first</span>`, `<b>Pratique</b><span>Le meilleur outil pour l'étape du jour, en premier</span>`],
  [`Welding English: workplace lines to shadow, spoken by the recruiter and the supervisor`, `Anglais du soudage${NB}: phrases de travail à imiter, dites par le recruteur et le chef d'équipe`],
  [`<b>Workplace lines</b><span>Hear the line, say it back, get a report</span>`, `<b>Phrases de travail</b><span>Écoutez la phrase, répétez-la, recevez un rapport</span>`],
  [`Welding English: workplace simulations, from the first day to the shift handover`, `Anglais du soudage${NB}: simulations de travail, du premier jour à la passation de poste`],
  [`<b>Workplace simulations</b><span>First day, handover, equipment, safety</span>`, `<b>Simulations de travail</b><span>Premier jour, passation, équipement, sécurité</span>`],
  [`Welding English: career destination, readiness and the interview coaches`, `Anglais du soudage${NB}: objectif de carrière, préparation et coachs d'entretien`],
  [`<b>Career and interviews</b><span>Your destination, readiness and coaches</span>`, `<b>Carrière et entretiens</b><span>Votre objectif, votre préparation et vos coachs</span>`],
  [`Welding English: progress for the welding programme only`, `Anglais du soudage${NB}: la progression du programme soudage uniquement`],
  [`<b>Your own progress</b><span>Kept apart from General English</span>`, `<b>Votre propre progression</b><span>Séparée de l'Anglais général</span>`],

  // 12 pricing
  [`<span class="n">12</span> Pricing</span>`, `<span class="n">12</span> Tarifs</span>`],
  [`<h2>Free <span class="grad">to start</span>.</h2>`, `<h2>Gratuit <span class="grad">pour commencer</span>.</h2>`],
  [`The twelve-week programme, Shadow Studio, the AI coach, Practice Partner and your progress are free today. No card needed.`,
   `Le programme de douze semaines, Shadow Studio, le coach IA, Practice Partner et votre progression sont gratuits aujourd'hui. Aucune carte bancaire requise.`],
  [`<span class="tag">Available now</span>`, `<span class="tag">Disponible maintenant</span>`],
  [`<div class="price"><b>Free</b></div>`, `<div class="price"><b>Gratuit</b></div>`],
  [`The whole programme, on iPhone and Android.`, `Tout le programme, sur iPhone et Android.`],
  [`<span>84 guided 25-minute sessions across 12 weeks</span>`, `<span>84 séances guidées de 25 minutes sur 12 semaines</span>`],
  [`<span>Shadow Studio, the speaking report and Executive Polish</span>`, `<span>Shadow Studio, le rapport oral et Executive Polish</span>`],
  [`<span>Practice Partner with live calls, on General English (18+)</span>`, `<span>Practice Partner avec appels en direct, dans l'Anglais général (18${NB}ans et plus)</span>`],
  [`<span>Guidance in 15 languages, and it works offline</span>`, `<span>Accompagnement en 15 langues, et fonctionne hors ligne</span>`],
  [`data-ev-source="pricing">
          Get the app`, `data-ev-source="pricing">
          ${GET}`],
  [`<span class="tag soon">In preparation</span>`, `<span class="tag soon">En préparation</span>`],
  [`One subscription for both programmes, for learners who practise every day. It is not on sale yet — when it is, the price will be shown here and in the store.`,
   `Un seul abonnement pour les deux programmes, pour celles et ceux qui pratiquent chaque jour. Il n'est pas encore en vente — quand il le sera, le prix sera indiqué ici et dans la boutique.`],
  [`<span>Many more AI speaking reports and coach replies every day</span>`, `<span>Beaucoup plus de rapports oraux IA et de réponses du coach chaque jour</span>`],
  [`<span>Your own YouTube videos, transcribed for shadowing</span>`, `<span>Vos propres vidéos YouTube, transcrites pour le shadowing</span>`],
  [`<span>30- and 90-day progress, and recommendations picked for you</span>`, `<span>La progression sur 30 et 90 jours, et des recommandations choisies pour vous</span>`],
  [`<span>The larger home-screen widgets and the Recommendations widget</span>`, `<span>Les grands widgets d'écran d'accueil et le widget Recommandations</span>`],

  // 13 FAQ
  [`<h2>Before you <span class="grad">download</span>.</h2>`, `<h2>Avant de <span class="grad">télécharger</span>.</h2>`],
  [`<summary>Is BE Mastery free?`, `<summary>BE Mastery est-il gratuit${NB}?`],
  [`<p>Yes. The full twelve-week programme, Shadow Studio, the AI coach, Practice Partner and your progress are free today, with no card needed. A Premium plan is on its way; its price will be shown before anything is charged.</p>`,
   `<p>Oui. Le programme complet de douze semaines, Shadow Studio, le coach IA, Practice Partner et votre progression sont gratuits aujourd'hui, sans carte bancaire. Une formule Premium arrive${NB}; son prix sera indiqué avant tout paiement.</p>`],
  [`<summary>Do I need an account?`, `<summary>Faut-il un compte${NB}?`],
  [`<p>No. You can start straight away. Sign in with Apple, Google or email when you want your progress backed up — then it follows you between your iPhone and your Android phone.</p>`,
   `<p>Non. Vous pouvez commencer tout de suite. Connectez-vous avec Apple, Google ou une adresse e-mail quand vous voulez sauvegarder votre progression — elle vous suit alors entre votre iPhone et votre téléphone Android.</p>`],
  [`<summary>What level do I need?`, `<summary>Quel niveau faut-il${NB}?`],
  [`<p>If you can read English but freeze when you speak, you are the learner it was built for. A short check at the start places you, and a gentler Foundations stage is there if you need it.</p>`,
   `<p>Si vous lisez l'anglais mais vous figez à l'oral, l'app a été conçue pour vous. Un court test au départ vous situe, et une étape Fondations plus douce est là si vous en avez besoin.</p>`],
  [`<summary>Can I use it in my own language?`, `<summary>Puis-je l'utiliser dans ma langue${NB}?`],
  [`<p>The guidance, menus and help are available in 15 languages, including French, Spanish, Portuguese and Arabic. The practice itself is in English.</p>`,
   `<p>L'accompagnement, les menus et l'aide existent en 15 langues, dont le français, l'espagnol, le portugais et l'arabe. La pratique elle-même se fait en anglais.</p>`],
  [`<summary>Is it on iPhone and Android?`, `<summary>Est-ce disponible sur iPhone et Android${NB}?`],
  [`<p>Yes. BE Mastery is on Google Play now, and the iPhone app is with Apple for review. Sign in with the same account on both and your progress, words and reports come with you.</p>`,
   `<p>Oui. BE Mastery est sur Google Play dès maintenant, et l'app iPhone est en cours d'examen chez Apple. Connectez-vous avec le même compte sur les deux et votre progression, vos mots et vos rapports vous suivent.</p>`],
  [`<summary>Who hears my recordings?`, `<summary>Qui entend mes enregistrements${NB}?`],
  [`<p>Your recordings are saved on your own device. To score a take, it is sent securely to our AI provider and not kept by us. Practice Partner live calls are never recorded.</p>`,
   `<p>Vos enregistrements restent sur votre propre appareil. Pour noter une prise, elle est envoyée de façon sécurisée à notre fournisseur d'IA, et nous ne la conservons pas. Les appels en direct de Practice Partner ne sont jamais enregistrés.</p>`],
  [`<summary>Is Practice Partner safe?`, `<summary>Practice Partner est-il sûr${NB}?`],
  [`<p>It is for adults (18+), shows first names only, and has no photos or profiles. You can leave, block or report at any time.</p>`,
   `<p>Il s'adresse aux adultes (18${NB}ans et plus), n'affiche que les prénoms et n'a ni photos ni profils. Vous pouvez partir, bloquer ou signaler à tout moment.</p>`],
  [`<summary>Is there a programme for my trade?`, `<summary>Existe-t-il un programme pour mon métier${NB}?`],
  [`<p>Yes, for welding and the trades around it: welders, pipefitters, boilermakers, millwrights, refinery operators, instrumentation technicians, industrial electricians, HSE officers, NDT technicians and process engineers. Choose Welding English when you open the app.</p>`,
   `<p>Oui, pour le soudage et les métiers qui l'entourent${NB}: soudeurs, tuyauteurs, chaudronniers, mécaniciens industriels, opérateurs de raffinerie, techniciens instrumentation, électriciens industriels, responsables HSE, techniciens CND et ingénieurs procédés. Choisissez Anglais du soudage à l'ouverture de l'app.</p>`],
  [`<summary>Is the certificate an English test?`, `<summary>Le certificat est-il un test d'anglais${NB}?`],
  [`<p>No. It shows you completed the programme, with your name on it. It is not a level test.</p>`,
   `<p>Non. Il atteste que vous avez terminé le programme, à votre nom. Ce n'est pas un test de niveau.</p>`],

  // 14 download + footer
  [`<span class="n">14</span> Get the app</span>`, `<span class="n">14</span> ${GET}</span>`],
  [`<h2>Your speaking practice <span class="grad">goes with you</span>.</h2>`, `<h2>Votre pratique orale <span class="grad">vous suit partout</span>.</h2>`],
  [`Twenty-five minutes on the train, in the car park, before the meeting. The app records, scores and remembers — and a partner can be waiting when you open it.`,
   `Vingt-cinq minutes dans le train, sur le parking, avant la réunion. L'app enregistre, note et se souvient — et un partenaire peut vous attendre quand vous l'ouvrez.`],
  [`<li><b>iPhone &amp; Android</b><span>One account, both phones</span></li>`, `<li><b>iPhone et Android</b><span>Un compte, deux téléphones</span></li>`],
  [`<li><b>Free</b><span>No card, no trial timer</span></li>`, `<li><b>Gratuit</b><span>Sans carte, sans période d'essai</span></li>`],
  [`<li><b>Offline</b><span>Practise with no signal</span></li>`, `<li><b>Hors ligne</b><span>Pratiquez sans réseau</span></li>`],
  [`<li><b>15 languages</b><span>Guidance in your own</span></li>`, `<li><b>15 langues</b><span>Un accompagnement dans la vôtre</span></li>`],
  [`<p>Build the confidence to speak when it matters.</p>`, `<p>Gagnez l'assurance de parler quand ça compte.</p>`],
  [`<a href="/">LOMON EC LLC</a>`, `<a href="/fr/">LOMON EC LLC</a>`],
];
