/* lomonec.com company page — English → French. Each entry is an exact
   string from site/index.html and its French replacement. */
const NB = "\u00a0"; // French spacing before : ; ? ! and inside « »

export default [
  // head
  [`Lomonec — AI automation, agentic AI and software`, `Lomonec — automatisation IA, IA agentique et logiciels`],
  [`Lomonec builds AI automation, AI agents and software for small service businesses, and makes its own apps, starting with BE Mastery. Book an AI Automation Quick Audit.`,
   `Lomonec conçoit des automatisations IA, des agents IA et des logiciels pour les petites entreprises de services, et crée ses propres apps, à commencer par BE Mastery. Réservez un audit express d'automatisation IA.`],
  [`<link rel="canonical" href="https://lomonec.com/">`, `<link rel="canonical" href="https://lomonec.com/fr/">`],
  [`<meta property="og:url" content="https://lomonec.com/">`, `<meta property="og:url" content="https://lomonec.com/fr/">`],
  [`AI automation for small service businesses, software development, and our own apps. Start with an AI Automation Quick Audit.`,
   `Automatisation IA pour les petites entreprises de services, développement logiciel et nos propres apps. Commencez par un audit express d'automatisation IA.`],
  [`AI automation for small service businesses, software development, and our own apps.`,
   `Automatisation IA pour les petites entreprises de services, développement logiciel et nos propres apps.`],

  // bar
  [`>Skip to content<`, `>Aller au contenu<`],
  [`aria-label="Main"`, `aria-label="Principal"`],
  [`aria-label="Lomonec home"`, `aria-label="Accueil Lomonec"`],
  [`aria-label="Open menu"`, `aria-label="Ouvrir le menu"`],
  [`<a href="#industries">Industries</a>`, `<a href="#industries">Secteurs</a>`],
  [`<a href="#how">How it works</a>`, `<a href="#how">Comment ça marche</a>`],
  [`<span>Book an audit</span>`, `<span>Réserver un audit</span>`],
  [`<summary aria-label="Language: English">`, `<summary aria-label="Langue${NB}: français">`],
  [`<span>EN</span><svg class="chev"`, `<span>FR</span><svg class="chev"`],
  [`lang="en" aria-current="true"`, `lang="en" aria-current="false"`],
  [`lang="fr" aria-current="false"`, `lang="fr" aria-current="true"`],
  [`href="/bemastery/"`, `href="/bemastery/fr/"`],

  // hero
  [`AI automation · Agentic AI · Software · Apps`, `Automatisation IA · IA agentique · Logiciels · Apps`],
  [`Software and AI that take the busywork off your desk.`, `Des logiciels et de l'IA qui vous débarrassent des tâches répétitives.`],
  [`Lomonec builds AI automations and AI agents for small service businesses, develops software, and makes its own apps. We start with the simple automations that pay off first: faster replies to leads, fewer no-shows, less copy-paste admin.`,
   `Lomonec conçoit des automatisations et des agents IA pour les petites entreprises de services, développe des logiciels et crée ses propres apps. Nous commençons par les automatisations simples qui rapportent en premier${NB}: des réponses plus rapides aux prospects, moins de rendez-vous manqués, moins de copier-coller administratif.`],
  [`>Book a Quick Audit<`, `>Réserver un audit express<`],
  [`>See our apps<`, `>Voir nos apps<`],

  // services
  [`<h2 class="eyebrow">What we do</h2>`, `<h2 class="eyebrow">Ce que nous faisons</h2>`],
  [`Four kinds of work, one aim: less manual effort.`, `Quatre types de travail, un seul but${NB}: moins d'effort manuel.`],
  [`<h3>AI automation consulting</h3><p>We find the repetitive work in your day and automate it: missed-call follow-up, reminders, quote chasing, review requests.</p>`,
   `<h3>Conseil en automatisation IA</h3><p>Nous repérons le travail répétitif de vos journées et l'automatisons${NB}: relance des appels manqués, rappels, suivi des devis, demandes d'avis.</p>`],
  [`<h3>Agentic AI</h3><p>AI agents that answer common questions, capture leads and hand the conversation to your staff with full context.</p>`,
   `<h3>IA agentique</h3><p>Des agents IA qui répondent aux questions courantes, captent les prospects et passent la conversation à votre équipe avec tout le contexte.</p>`],
  [`<h3>Software development</h3><p>Web apps, mobile apps and the back-end services behind them, built and maintained by the same team.</p>`,
   `<h3>Développement logiciel</h3><p>Applications web, applications mobiles et les services back-end qui les font tourner, conçus et maintenus par la même équipe.</p>`],
  [`<h3>Our own apps</h3><p>We build and publish our own products. The first is BE Mastery, an English speaking practice app.</p>`,
   `<h3>Nos propres apps</h3><p>Nous concevons et publions nos propres produits. Le premier est BE Mastery, une app pour pratiquer l'anglais à l'oral.</p>`],

  // apps
  [`<h2 class="eyebrow">Our apps</h2>`, `<h2 class="eyebrow">Nos apps</h2>`],
  [`Apps made by Lomonec.`, `Des apps créées par Lomonec.`],
  [`<p class="mc-tag">English speaking practice</p>`, `<p class="mc-tag">Pratique de l'anglais oral</p>`],
  [`Practise speaking English for 25 minutes a day: a 12-week plan, shadowing, an AI coach and real learners. General English and Welding English.`,
   `Pratiquez l'anglais à l'oral 25 minutes par jour${NB}: un plan de 12 semaines, du shadowing, un coach IA et de vrais apprenants. Anglais général et Anglais du soudage.`],
  [`On Google Play now. With Apple for review.`, `Sur Google Play dès maintenant. En cours d'examen chez Apple.`],
  [`Explore BE Mastery →`, `Découvrir BE Mastery →`],
  [`<p class="mc-tag">In development</p><h3>More apps on the way</h3><p>New Lomonec apps will be listed here as they are released.</p>`,
   `<p class="mc-tag">En développement</p><h3>D'autres apps arrivent</h3><p>Les nouvelles apps Lomonec seront présentées ici à leur sortie.</p>`],

  // automation
  [`<h2 class="eyebrow">AI automation for service businesses</h2>`, `<h2 class="eyebrow">Automatisation IA pour les entreprises de services</h2>`],
  [`Stop losing leads and wasting staff time on repetitive admin.`, `Arrêtez de perdre des prospects et de gaspiller le temps de votre équipe en tâches administratives répétitives.`],
  [`<h3 class="sub">Is this you?</h3>`, `<h3 class="sub">Vous vous reconnaissez${NB}?</h3>`],
  [`<span>Missed calls or slow lead response</span>`, `<span>Appels manqués ou réponses lentes aux prospects</span>`],
  [`<span>Too much time on repetitive follow-up</span>`, `<span>Trop de temps passé sur des relances répétitives</span>`],
  [`<span>No-shows and manual reminders</span>`, `<span>Rendez-vous manqués et rappels faits à la main</span>`],
  [`<span>Quote requests that go cold</span>`, `<span>Des demandes de devis qui refroidissent</span>`],
  [`<span>The same questions answered over and over, by people</span>`, `<span>Les mêmes questions traitées encore et encore, à la main</span>`],
  [`<span>Staff doing copy-paste admin work</span>`, `<span>Une équipe occupée à du copier-coller administratif</span>`],
  [`<h3 class="sub">What we automate</h3>`, `<h3 class="sub">Ce que nous automatisons</h3>`],
  [`<h3>Missed-call follow-up</h3><p>Recover leads that would otherwise be lost.</p>`, `<h3>Relance des appels manqués</h3><p>Récupérez des prospects qui seraient sinon perdus.</p>`],
  [`<h3>Appointment reminders</h3><p>Fewer no-shows and reschedules.</p>`, `<h3>Rappels de rendez-vous</h3><p>Moins d'absences et de reports.</p>`],
  [`<h3>Quote and estimate follow-up</h3><p>Convert more pending jobs.</p>`, `<h3>Suivi des devis et estimations</h3><p>Transformez davantage de demandes en chantiers.</p>`],
  [`<h3>Customer FAQs</h3><p>Fewer repetitive messages.</p>`, `<h3>FAQ clients</h3><p>Moins de messages répétitifs.</p>`],
  [`<h3>Review requests</h3><p>More Google reviews.</p>`, `<h3>Demandes d'avis</h3><p>Plus d'avis Google.</p>`],
  [`<h3>Invoice and payment reminders</h3><p>Better collections.</p>`, `<h3>Rappels de factures et de paiements</h3><p>De meilleurs encaissements.</p>`],
  [`<h3>Internal admin</h3><p>Data entry, updates, summaries, reporting.</p>`, `<h3>Administration interne</h3><p>Saisie de données, mises à jour, synthèses, reporting.</p>`],

  // example
  [`<h2 class="eyebrow">Example automation</h2>`, `<h2 class="eyebrow">Exemple d'automatisation</h2>`],
  [`Missed-call text-back.`, `Le SMS après un appel manqué.`],
  [`What happens when a customer calls and nobody can pick up.`, `Ce qui se passe quand un client appelle et que personne ne peut décrocher.`],
  [`<b>Customer calls your business</b><span>You're with a client, on a job, or it's after hours.</span>`,
   `<b>Un client appelle votre entreprise</b><span>Vous êtes avec un client, sur un chantier, ou c'est après la fermeture.</span>`],
  [`<b>The call goes unanswered</b><span>Without automation, the lead calls the next business on Google.</span>`,
   `<b>L'appel reste sans réponse</b><span>Sans automatisation, le prospect appelle l'entreprise suivante sur Google.</span>`],
  [`<li class="flow-gap">within 30 seconds</li>`, `<li class="flow-gap">en moins de 30 secondes</li>`],
  [`<b>An instant text goes out automatically</b><span>“Hi, this is [Business]. Sorry we missed your call — how can we help? Book directly here: [link]”</span>`,
   `<b>Un SMS part aussitôt, automatiquement</b><span>«${NB}Bonjour, ici [Entreprise]. Désolés d'avoir manqué votre appel — comment pouvons-nous vous aider${NB}? Réservez directement ici${NB}: [lien]${NB}»</span>`],
  [`<b>The lead replies by text</b><span>The conversation is captured and routed to you or your staff with full context.</span>`,
   `<b>Le prospect répond par SMS</b><span>La conversation est enregistrée et transmise à vous ou à votre équipe avec tout le contexte.</span>`],
  [`<b>The lead books via the link</b><span>The appointment lands on your calendar. No phone tag.</span>`,
   `<b>Le prospect réserve via le lien</b><span>Le rendez-vous arrive dans votre agenda. Sans rappels à n'en plus finir.</span>`],
  [`<b>Automatic reminder before the appointment</b><span>A confirmation and reminder sequence cuts no-shows.</span>`,
   `<b>Rappel automatique avant le rendez-vous</b><span>Une confirmation puis des rappels réduisent les absences.</span>`],
  [`<b>Review request after the visit</b><span>Happy customer → Google review → more calls next month.</span>`,
   `<b>Demande d'avis après la visite</b><span>Client satisfait → avis Google → plus d'appels le mois suivant.</span>`],
  [`<b>&lt; 30 sec</b><span>to reply to every missed call</span>`, `<b>&lt; 30 s</b><span>pour répondre à chaque appel manqué</span>`],
  [`<span>works after hours and at weekends</span>`, `<span>fonctionne après la fermeture et le week-end</span>`],
  [`<b>Hands-off</b><span>no staff action to send the reply once live</span>`, `<b>Sans intervention</b><span>aucune action de l'équipe pour envoyer la réponse une fois en place</span>`],

  // industries
  [`<h2 class="eyebrow">Who it's for</h2>`, `<h2 class="eyebrow">Pour qui</h2>`],
  [`Local businesses with a lot of client messages and bookings.`, `Les entreprises locales qui gèrent beaucoup de messages clients et de réservations.`],
  [`<p class="mc-tag">Salons, braiding and beauty</p><h3>Your chairs should be full — not your voicemail.</h3>`,
   `<p class="mc-tag">Coiffure, tresses et beauté</p><h3>Vos fauteuils doivent être pleins — pas votre messagerie.</h3>`],
  [`<li>Missed-call text-back that captures the booking</li>`, `<li>SMS après appel manqué qui capte la réservation</li>`],
  [`<li>Automatic appointment reminders</li>`, `<li>Rappels de rendez-vous automatiques</li>`],
  [`<li>Instant answers on pricing, hours and availability</li>`, `<li>Réponses immédiates sur les tarifs, les horaires et les disponibilités</li>`],
  [`<li>Review requests and rebooking nudges after each visit</li>`, `<li>Demandes d'avis et invitations à reprendre rendez-vous après chaque visite</li>`],
  [`<li>Intake forms routed to the right stylist</li>`, `<li>Formulaires d'accueil transmis au bon coiffeur</li>`],
  [`<p class="mc-tag">Clinics, med spas, dental and therapy</p><h3>Less admin. Fewer no-shows. Better patient communication.</h3>`,
   `<p class="mc-tag">Cliniques, médecine esthétique, dentistes et thérapeutes</p><h3>Moins d'administratif. Moins d'absences. Une meilleure communication avec les patients.</h3>`],
  [`<li>Appointment reminder and confirmation sequences</li>`, `<li>Séquences de rappel et de confirmation de rendez-vous</li>`],
  [`<li>Intake follow-up before the visit, not in the lobby</li>`, `<li>Formulaires d'accueil remplis avant la visite, pas dans la salle d'attente</li>`],
  [`<li>FAQ workflows for hours, insurance and preparation</li>`, `<li>Réponses automatiques sur les horaires, l'assurance et la préparation</li>`],
  [`<li>Post-visit follow-up and review requests</li>`, `<li>Suivi après la visite et demandes d'avis</li>`],
  [`<li>Recall and rebooking reminders for due patients</li>`, `<li>Rappels de suivi et de nouveau rendez-vous pour les patients concernés</li>`],
  [`<p class="mc-tag">Cleaning, HVAC, plumbing, roofing, handyman</p><h3>The fastest quote usually wins the job.</h3>`,
   `<p class="mc-tag">Nettoyage, chauffage et climatisation, plomberie, toiture, petits travaux</p><h3>Le devis le plus rapide remporte généralement le chantier.</h3>`],
  [`<li>Missed-call text-back and website lead capture</li>`, `<li>SMS après appel manqué et capture des prospects du site web</li>`],
  [`<li>Automatic quote and estimate follow-up</li>`, `<li>Suivi automatique des devis et estimations</li>`],
  [`<li>Appointment and job reminders</li>`, `<li>Rappels de rendez-vous et d'interventions</li>`],
  [`<li>Review requests after every completed job</li>`, `<li>Demandes d'avis après chaque intervention terminée</li>`],
  [`<li>Invoice and payment reminders that don't feel awkward</li>`, `<li>Rappels de factures et de paiements, sans gêne</li>`],
  [`Also real estate and other local businesses with repetitive client communication and scheduling.`,
   `Également l'immobilier et d'autres entreprises locales dont la communication client et la prise de rendez-vous sont répétitives.`],

  // how it works
  [`<h2 class="eyebrow">How it works</h2>`, `<h2 class="eyebrow">Comment ça marche</h2>`],
  [`Start small. Scale when the value is proven.`, `Commencez petit. Développez quand la valeur est prouvée.`],
  [`<h3>Quick Audit</h3><p>A focused 60–75 minute session on one or two of your workflows. You get a prioritised 30-day roadmap and a simple ROI snapshot.</p>`,
   `<h3>Audit express</h3><p>Une séance ciblée de 60 à 75 minutes sur un ou deux de vos processus. Vous recevez une feuille de route priorisée sur 30 jours et une estimation simple du retour sur investissement.</p>`],
  [`<h3>Quick win</h3><p>We recommend the one automation with the best payoff for your business, and can set it up for you.</p>`,
   `<h3>Premier gain rapide</h3><p>Nous recommandons l'automatisation la plus rentable pour votre entreprise, et pouvons la mettre en place pour vous.</p>`],
  [`<h3>Scale what works</h3><p>Add more automations only when the first one proves its value. You choose what to implement, with us or on your own.</p>`,
   `<h3>Développer ce qui marche</h3><p>N'ajoutez d'autres automatisations que lorsque la première a prouvé sa valeur. Vous choisissez quoi mettre en place, avec nous ou par vous-même.</p>`],
  [`The audit stands on its own. There is never an obligation to continue.`, `L'audit se suffit à lui-même. Vous n'êtes jamais obligé de continuer.`],

  // roadmap
  [`<h2 class="eyebrow">What the audit gives you</h2>`, `<h2 class="eyebrow">Ce que vous apporte l'audit</h2>`],
  [`A 30-day roadmap you can act on.`, `Une feuille de route sur 30 jours, prête à appliquer.`],
  [`An example for a small salon. Every business gets its own plan.`, `Un exemple pour un petit salon. Chaque entreprise reçoit son propre plan.`],
  [`<span class="mc-week">Week 1</span>`, `<span class="mc-week">Semaine 1</span>`],
  [`<span class="mc-week">Week 2</span>`, `<span class="mc-week">Semaine 2</span>`],
  [`<span class="mc-week">Week 3</span>`, `<span class="mc-week">Semaine 3</span>`],
  [`<span class="mc-week">Week 4</span>`, `<span class="mc-week">Semaine 4</span>`],
  [`<h3>Quick win: missed-call text-back</h3><p>Every unanswered call triggers an instant text with a booking link. Set up, tested with staff phones, launched.</p>`,
   `<h3>Gain rapide${NB}: SMS après appel manqué</h3><p>Chaque appel sans réponse déclenche un SMS immédiat avec un lien de réservation. Configuré, testé avec les téléphones de l'équipe, lancé.</p>`],
  [`<h3>Appointment reminders</h3><p>A confirmation at booking, reminders 48 hours and 3 hours before, and an easy reschedule link.</p>`,
   `<h3>Rappels de rendez-vous</h3><p>Une confirmation à la réservation, des rappels 48 heures et 3 heures avant, et un lien simple pour reporter.</p>`],
  [`<h3>Review requests</h3><p>Two hours after checkout, clients get a thank-you text with a direct Google review link. One gentle nudge for non-responders.</p>`,
   `<h3>Demandes d'avis</h3><p>Deux heures après leur passage, les clients reçoivent un SMS de remerciement avec un lien direct vers les avis Google. Une relance discrète pour ceux qui n'ont pas répondu.</p>`],
  [`<h3>Measure and tune</h3><p>Review recovered leads, no-show rate and review count. Adjust timing and wording. Decide on phase 2.</p>`,
   `<h3>Mesurer et ajuster</h3><p>Examinez les prospects récupérés, le taux d'absence et le nombre d'avis. Ajustez le moment et la formulation. Décidez de la phase 2.</p>`],

  // contact + footer
  [`<h2>Book your AI Automation Quick Audit</h2>`, `<h2>Réservez votre audit express d'automatisation IA</h2>`],
  [`Tell us about your business and the work you'd like to stop doing by hand. We'll reply to arrange a time.`,
   `Parlez-nous de votre entreprise et du travail que vous aimeriez ne plus faire à la main. Nous vous répondrons pour fixer un rendez-vous.`],
  [`subject=AI%20Automation%20Quick%20Audit`, `subject=Audit%20express%20automatisation%20IA`],
  [`>Email contact@lomonec.com<`, `>Écrire à contact@lomonec.com<`],
  [`<p>AI automation, agentic AI, software and apps.</p>`, `<p>Automatisation IA, IA agentique, logiciels et apps.</p>`],
];
